env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: "airbnb"
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
globals:
  React: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-filename-extension: 
    - warn
    - extensions:
      - ".js"
      - ".jsx"
